#!/usr/bin/bash

function _copy_main_tex() {
    cp $TEXTEMP/latex/gitignore ${PWD}/$1/.gitignore
    if [ "$2" = "-ac" ]; then
        cp $TEXTEMP/latex/main.bib ${PWD}/$1
        cp $TEXTEMP/latex/article_main_code.tex ${PWD}/$1/main.tex
        cp -r $TEXTEMP/latex/images ${PWD}/$1
        cp -r $TEXTEMP/latex/src ${PWD}/$1
        cp $TEXTEMP/latex/Makefile ${PWD}/$1
        return
    elif [ "$2" = "-a" ]; then
        cp $TEXTEMP/latex/main.bib ${PWD}/$1
        cp $TEXTEMP/latex/article_main.tex ${PWD}/$1/main.tex
        cp -r $TEXTEMP/latex/images ${PWD}/$1
        cp -r $TEXTEMP/latex/src ${PWD}/$1
        cp $TEXTEMP/latex/Makefile ${PWD}/$1
        return
    elif [ "$2" = "-ec" ]; then
        cp $TEXTEMP/latex/main.bib ${PWD}/$1
        cp $TEXTEMP/latex/exercise_main_code.tex ${PWD}/$1/main.tex
        cp $TEXTEMP/latex/Makefile_simp ${PWD}/$1/Makefile
        return
    elif [ "$2" = "-e" ]; then
        cp $TEXTEMP/latex/main.bib ${PWD}/$1
        cp $TEXTEMP/latex/exercise_main.tex ${PWD}/$1/main.tex
        cp $TEXTEMP/latex/Makefile_simp ${PWD}/$1/Makefile
        return
    elif [ "$2" = "-IEEE" ]; then
        cp $TEXTEMP/latex/main.bib ${PWD}/$1
        cp $TEXTEMP/latex/IEEE.tex ${PWD}/$1/main.tex
        cp $TEXTEMP/latex/cls/IEEEtran.cls ${PWD}/$1/IEEEtran.cls
        cp $TEXTEMP/latex/Makefile_simp ${PWD}/$1/Makefile
        return
    elif [ "$2" = "-pres" ]; then
        cp $TEXTEMP/latex/presentation-temp.tex ${PWD}/$1/main.tex
        cp $TEXTEMP/latex/Makefile_pres ${PWD}/$1/Makefile
        return
    fi
}

function _create_template() {
    mkdir ${PWD}/$1
    _copy_main_tex $@
}

function _check_response(){
    if [[ "$1" == "Y" || "$1" == "y" ]]; then
        echo 0
    elif [[ "$1" == "N" || "$1" == "n" ]]; then
        echo 1
    else
        echo 2
    fi
}

function _check_args() {
    if [[ "$1" == -h ]]; then
        printf "textemp, generate Folders with simple and easy to use LaTeX templates using a single command.\n\nUsage: textemp [FOLDER] -[FLAG]\nFLAG options:\n\t-a\t\t: Article template for simple Articles\n\t-ac\t\t: Article Template with code listings\n\t-e\t\t: Exercise Template for Exercises (Good for Uni work)\n\t-ec\t\t: Exercise Template with code listings\n\t-IEEE\t: The IEEE-Trans Template\n\t-pres\t: LaTeX beamer template presentation\n"
        return 1
    elif [ $# -ne 2 ]; then
        echo "Invalid number of arguments"
        return 1
    elif [[ "$1" =~ ^- ]]; then
        echo "Invalid folder name"
        return 1
    fi
    case $2 in
        "-a" | "-ac" | "-e" | "-ec" | "-IEEE" | "-pres" )
            :;;
        *)
            echo "Invalid flag"
            return 1;;
    esac
    return 0
}

BGREEN=$'\033[4;32m'
_check_args $@
if [ "$?" != "0" ]; then
    exit 1
elif [ -e ${PWD}/$1 ]; then
    printf "The folder already exists. Overwrite it? (y/n): "
    read -r create
    response=$(_check_response $create)
    if [[ "$response" == "0" ]]; then
        rm -r $PWD/$1
        _create_template $@
    else
        echo "Exiting"
        exit 1
    fi
else
    _create_template $@
fi
printf "${GREEN}Finished setting up template in ${BGREEN}$PWD/$1\n"
