#!/usr/bin/env bash

function _copy_main_tex() {
    for arg in "$@"
    do
        if [ "$arg" = "-c" ]; then
            cp $1/latex/article_main_code.tex ${PWD}/$2/main.tex
            return
        fi
    done
    cp $1/latex/article_main.tex ${PWD}/$2/main.tex
}

function _create_template() {
    mkdir ${PWD}/$2
    cp $1/latex/main.bib ${PWD}/$2
    cp $1/latex/Makefile ${PWD}/$2
    cp -r $1/latex/images ${PWD}/$2
    cp -r $1/latex/src ${PWD}/$2
    _copy_main_tex $@
}

function textemp() {
    DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )/textemp"
    if [ -e ${PWD}/$1 ]; then
        echo "The folder already exists exists"
    else
        _create_template $DIR $@
    fi
}